name: test
on: [push, pull_request]

env:
  PYTHON_VERSION: 3.9

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Install NODE JS
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install project
      run: yarn install

    - name: Install dependencies
      run: yarn install-peers

    - name: Compile
      run: yarn compile

    - name: lint
      run: yarn fullCheck
